name: CI

on: [push]

defaults:
  run:
    working-directory: node-typescript-ci

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: node-typescript-ci/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Docker Build
        run: docker build -t node-typescript-ci .

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::719514706718:role/github-actions-freelance-templates
          aws-region: us-east-1

      - name: Verify AWS connection
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push Docker image to ECR
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: node-typescript-ci
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag node-typescript-ci:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag node-typescript-ci:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY$ECR_REPOSITORY:latest