name: CI

on:
  push:
    paths:
      - 'node-typescript-ci/**'
      - '.github/workflows/**'

defaults:
  run:
    working-directory: node-typescript-ci

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: node-typescript-ci/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Docker Build
        run: docker build -t node-typescript-ci .

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::719514706718:role/github-actions-freelance-templates
          aws-region: us-east-1

      - name: Verify AWS connection
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push Docker image to ECR
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: node-typescript-ci
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag node-typescript-ci:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag node-typescript-ci:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Render ECS task definition
        id: render-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: node-typescript-ci/task-definition.json
          container-name: node-typescript-ci
          image: ${{ steps.login-ecr.outputs.registry }}/node-typescript-ci:${{ github.sha }}
          environment-variables: "COMMIT_SHA=${{ github.sha }}"

      - name: Deploy ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          service: node-typescript-ci-service
          cluster: freelance-templates-cluster
          wait-for-service-stability: true